version: '3.8'

services:
  data-clean:
    image: docker.cnb.cool/huanglixian/gdy-docker/data-clean:latest
    container_name: data-clean
    ports:
      - "8419:8419"
    volumes:
      # 数据卷映射
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8419/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s